theme: minima
title: My blog and porfolio
author: Guillem Roca
email: guillemroc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my the blog and porfolio of projects I've worked 
  and experimente with. There will be tips and tricks of Android
  and random thoughts as well.

# social links
twitter_username: 6uillemRoca
github_username:  GuillemRoca

show_excerpts: true # set to false to remove excerpts on the homepage
